name: student_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  file_picker: ^9.0.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  equatable: ^2.0.7
  archive: ^4.0.4
  xml: ^6.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Cairo-Regular.ttf  # إضافة الخط العربي
    - assets/logo/logo.jpg
    - assets/logo/logo2.jpg

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
